name: flutter_bloc_base
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.22
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  sentry_flutter: ^7.12.0
  google_fonts: ^6.1.0
  image: ^4.1.3
  flutter_gen: ^5.4.0
  intl: ^0.18.1
  material_color_utilities: ^0.5.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  bloc: ^8.1.2
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  dio: ^5.4.1
  package_info: ^2.0.2
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  freezed: ^2.5.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  colors:
    inputs:
      - assets/colors/colors.xml
